# Generated by Django 4.2.7 on 2023-11-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('Consul', 'Consul')], default='Consul', max_length=10)),
            ],
            options={
                'permissions': [('can_view_gastos', 'Puede ver gastos'), ('can_add_edit_delete_gastos', 'Puede agregar, editar y eliminar gastos')],
            },
        ),
    ]
